name: CI

on: workflow_dispatch

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: show_greet
        run: |
           echo "First line"
           echo "Second line"
      - name: show_goodbye
        run: echo "Done, Goodbye"
      
